### ISSUE TITLE
Software Architecture

### ISSUE THREAD

**Issue by jstephencorey** [ttocsneb/Rook#5]
- [x] Make The Software Architecture Document

**Comment by ttocsneb** [comment]
You can now access the document from [google drive](https://docs.google.com/document/d/1X6t3ZTFQ6liZ3Fe3_rh_UltwW6_utpnzvVkh9rBqoxM/edit?usp=sharing)

**Comment by ttocsneb** [comment]
I am pretty much finished, but I would like others to take a look and make any changes they feel are necessary
